gimBook/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using gimBook.Models;
using gimBook.ViewModels;
using gimBook.ViewModels.SmallView;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System.Runtime.Serialization.Json;

namespace gimBook.Controllers
{
    public class AjaxController : Controller
    {

        private DataBase Db = new DataBase();


        // GET: Ajax

        /*


            Metody AJAXowe
            Kontrolery służące zwracaniu danych asynchronicznych     

            1. GetSubject
            Na podstawie id będącego id przedmiotu znajduje listę ocen dla zalogowanego użytkownika.
            Dodatkowo pobiera listę średnich użytkownika z danego przedmiotu.


            TODO: SPRAWDŹ CZY TRZEBA CHILDONLY CZY KI CHUJ

        */


        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetStudentSubject(int id)
        {


            string userID = User.Identity.GetUserId();

            StudentSubjectViewModel Model = new StudentSubjectViewModel();


            Model.Grades = (
               from g in Db.grades
               where (g.subjectId == id)
               && (g.studentId == userID)
               orderby g.date descending
               select new tableGrades
               {
                   Date = g.date,
                   Grade = g.grade1,
                   Subject = g.subject,
                   Mult = g.mult
               }
               ).ToList();



            Model.Averages = (
                from a in Db.averages
                where (a.subjectId == id)
                && (a.studentId == userID)
                orderby a.date descending
                select new tableAverages
                {
                    Date = a.date,
                    Value = a.value
                }
                ).ToList();


            foreach (tableGrades grade in Model.Grades)
            {
                grade.DateStr = grade.Date.ToString("dd/MM/yy  HH:mm");
            }
            foreach (tableAverages average in Model.Averages)
            {
                average.DateStr = average.Date.ToString("dd/MM");
            }

            return Json(new {
                Grades = Model.Grades,
                Averages = Model.Averages
            }, JsonRequestBehavior.AllowGet
            );
        }

        public ActionResult TeacherTable(int id)
        {
            List<tableTeacherTableRow> Model = new List<tableTeacherTableRow>();

            Model = (
                from u in Db.AspNetUsers
                join c in Db.classes on u.ClassId equals c.id
                join s in Db.subjects on c.id equals s.classId
                where s.id == id
                select new tableTeacherTableRow
                {
                    FirstName = u.FirstName,
                    LastName = u.LastName,
                    Id = u.Id
                }).ToList();

            return Json(Model, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SendGrades(List<grade> Model)
        {

            //1. Zapisz nową ocenę do bazy
            foreach (grade g in Model)
            {
                /* Data ustalana jest w momencie dodawania do bazy */
                g.date = DateTime.Now;
                Db.grades.Add(g);
            }
            Db.SaveChanges();

            // Zapisz nowe średnie studentów do bazy.
            average newAv = new average();
            foreach (grade g in Model)
            {
                newAv.studentId = g.studentId;
                newAv.subjectId = g.subjectId;
                newAv.date = DateTime.Now;
                newAv.value = (
                    from gr in Db.grades
                    where gr.studentId == g.studentId
                    && gr.subjectId == g.subjectId
                    select (gr.grade1)
                    ).Average();

                Db.averages.Add(newAv);
                Db.SaveChanges();
            }
            
            /* Save changes musi być wywołane dwa razy aby brało pod uwagę średnią PO dodaniu ocen */


            return Content("Sukces!!");
        }
    }
}

gimBook/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using gimBook.Models;
using gimBook.ViewModels;
using gimBook.ViewModels.SmallView;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;

namespace gimBook.Controllers
{



    public class HomeController : Controller
    {
        
        private DataBase Db = new DataBase();

        public ActionResult Index()
        {

            

            /*

                   
                   Główny kontroler wartości wyświetlanych:
                        1. Sprawdź czy ktoś jest zalogowany
                        2. Jeśli jest, przypisz wartości wspólne
                            -- CurrentUser --
                            -- UserClass --
                            -- UserClassAverage --
                            -- SubjectList --
                        3. Na podstawie ClassID sprawdź czy to student, jeśli tak, przypisz wartości specyficzne
                            -- UserClass
                            -- LastThreeGrades --
                            -- UserAverage --
                            -- BestClass --
                            -- WorstClass --
                            -- AllGradesNum --
                        4. Zrobi inne rzeczy których nie chciało mi się tu opisywać, elo

 
             */

            if (Request.IsAuthenticated)
            {
                ViewModels.IndexViewModel Model = new ViewModels.IndexViewModel();

                // Current User
                string userID = User.Identity.GetUserId();
                
                Model.CurrentUser = Db.AspNetUsers.Single(g => g.Id == userID);
                int userClassId = Model.CurrentUser.ClassId;




                //  User Class Average
                /*  
                   
                    Query pobiera na podstawie klasy użytkownika 
                    (klasa zerowa nie bedzie posiadała ocen)
                    Lub na podstawie ocen klas których nauczycielem
                    jest uzytkownik


                */


                Model.UserClassAverage = (
                from a in Db.averages
                join s in Db.subjects on a.subjectId equals s.id
                join c in Db.classes on s.classId equals c.id
                where (c.id == userClassId)
                || (c.classTeacherId == userID)
                select (double?) a.value 
                ).Average() ?? 0;
                
                


                //Sprawdź czy jest to uczeń
                if(userClassId != 0)
                {
                    // User Class 1
                    Model.UserClass = this.Db.classes.Single(g => g.id == userClassId);

                    // Subject List 1
                    /*

                        Query pobiera albo wszystkie przedmioty ucznia
                        na podstawie połączenia przedmiot - klasa - uczeń

                     */
                    Model.SubjectList = (
                        from s in Db.subjects
                        join c in Db.classes on s.classId equals c.id
                        join u in Db.AspNetUsers on s.teacherId equals u.Id
                        where c.id == userClassId
                        select new TwoStringIntViewModel
                        {
                            Int = s.id,
                            Str1 = s.subjectName,
                            Str2 = u.LastName
                        }
                        ).ToList();



                    // LastThreeGrades (with subject names)
                    Model.LastThreeGrades = (
                           from g in Db.grades
                           join s in Db.subjects on g.subjectId equals s.id
                           where (g.studentId == userID)
                           orderby g.date descending
                           select new TwoStringIntViewModel
                           {
                               Int = g.grade1,
                               Str1 = s.subjectName,
                               Str2 = g.subject
                           }
                    ).Take(3).ToList();

                    // UserAverage
                    Model.UserAverage = (
                           from a in Db.averages
                           where (a.studentId == userID)
                           select (double?) a.value
                       ).Average() ?? 0;

                    // BestClass
                    Model.BestClass = (
                        from s in Db.subjects
                        join a in Db.averages on s.id equals a.subjectId
                        where a.studentId == userID
                        orderby a.value descending
                        select s.subjectName
                       ).FirstOrDefault();

                    // WorstClass
                    Model.WorstClass = (
                        from s in Db.subjects
                        join a in Db.averages on s.id equals a.subjectId
                        where a.studentId == userID
                        orderby a.value ascending
                        select s.subjectName
                       ).FirstOrDefault();

                    // AllGradesNumString
                    Model.AllGradesNum = (
                        from g in Db.grades
                        where g.studentId == userID
                        group g by g.grade1 into c
                        select new GradeNumViewModel
                            {
                                Grade = c.Key,
                                Count = c.Count()
                            }
                        ).ToList();

                }
                else // To jest Nauczyciel
                {

                    // User Class 1
                    Model.UserClass = this.Db.classes.Single(g => g.classTeacherId == userID);

                    // Subject List 2
                    /*

                        Jeśli jest to nauczyciel pobieramy parametry klasy miast 
                        Nazwiska nauczyciela

                     */
                    Model.SubjectList = (
                        from s in Db.subjects
                        join c in Db.classes on s.classId equals c.id
                        join u in Db.AspNetUsers on s.teacherId equals u.Id
                        where s.teacherId == userID
                        select new TwoStringIntViewModel
                        {
                            Int = s.id,
                            Str1 = s.subjectName,
                            Str2 = (c.classYear + " " + c.className)
                        }
                        ).ToList();

                    /*
                     * Lista studentów klasy
                     * Pobieramy tutaj tylko samą tablice studentów ale też całe ich dzienniki
                     * Przez to potrzebujemy dodatkowego obiektu zagniezdzonego
                     * W skrócie: New level obiektowość!
                     * 
                     * ps. Jeszcze w tym wewn. zapytaniu musimy joinować, to już w ogóle wow
                     */

                    Model.StudentList = (
                        from u in Db.AspNetUsers
                        where u.ClassId == Model.UserClass.id
                        select new StudentListViewModel
                        {
                            Id = u.Id,
                            FirstName = u.FirstName,
                            LastName = u.LastName,
                            EMail = u.Email,
                            Grades = (
                                from g in Db.grades //Z Ocen
                                join s in Db.subjects on g.subjectId equals s.id
                                where g.studentId == u.Id
                                orderby g.date descending
                                select new tableGrades
                                {
                                    Grade = g.grade1,
                                    Subject = g.subject,
                                    SubjectName = s.subjectName,
                                }
                            ).ToList()
                        }
                        ).ToList();
                    
                    
                }

                Model.GradeList = new GradeListViewModel();

                return View(Model);
            }
            else
            {
                // Jeśli nikt nie jest zalogowany, strona odsyła do strony logowania
                return RedirectToAction("Login", "Account");

            }
            

            //studentIndex.ClassList = this.Db.classes.ToList();

            

            
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }


        /*
         * Edycja Danych Studenta Przez Nauczyciela.
         * Dzieje się requestem Post
         * Tak dla zabawy, why not
         */

        public ActionResult EditStudent(string id)
        {
            //Tylko Nauczyciel Może zmieniać rekordy
            //Więc pobieramy jego klase
            string userID = User.Identity.GetUserId();
            int userClass = (
                from u in Db.AspNetUsers
                where u.Id == userID
                select u.ClassId
                ).FirstOrDefault();

            //I sprawdzamy czy sie zgadza
            if (userClass == 0)
            {
                StudentListViewModel Student = new StudentListViewModel();

                //Tutaj damy formularz z danymi studenta o określonym Id
                Student = (
                    from u in Db.AspNetUsers
                    where u.Id == id
                    select new StudentListViewModel

gimBook/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

gimBook/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

gimBook/Views/Home/EditStudent.cshtml
@model gimBook.ViewModels.SmallView.StudentListViewModel
@{
    ViewBag.Title = "EditStudent";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h1 class="text-info">
        Edytuj Dane Użytkownika
    </h1>
    @using (Html.BeginForm())
    {
        <div id="student-edit-form">
            <div class="form-group col-lg-4">
                <label for="FirstName">Imię</label>
                @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control btn-primary" })
            </div>
            <div class="form-group col-lg-4">
                <label for="LastName">Nazwisko</label>
                @Html.TextBoxFor(model => model.LastName, new { @class = "form-control btn-primary" })
            </div>
            <div class="form-group col-lg-4">
                <label for="FirstName">Email</label>
                @Html.TextBoxFor(model => model.EMail, new { @class = "form-control btn-primary" })
            </div>
            <input type="hidden" value="@Model.Id" name="Id" />
            <h1 class="form-group-lg text-right">
                <button class="btn-lg btn-danger" type="submit">Aktualizuj Dane Ucznia</button>
            </h1>
        </div>
    }
</div>

gimBook/Views/Home/Index.cshtml
@model gimBook.ViewModels.IndexViewModel

@{
    ViewBag.Title = "Home Page";
}


<!-- 
    ==================================================================================
        Strona najpierw sprawdza czy użytkownik jest zalogowany,
        Jeśli jest, ocenia czy jest to student czy nauczyciel na podstawie idKlasy
        Do każdego przekazywany jest model INDEXVIEW
    ==================================================================================
-->
@if (Model.CurrentUser.ClassId != 0)
    {
        Html.RenderPartial("_StudentIndexView", Model);
    }
else
    {
        Html.RenderPartial("_TeacherIndexView", Model);
    }

gimBook/Views/Home/_NotLoggedIndexView.cshtml
<!--
    ==================================================================================
        Strona dla niezalogowanego użytkownika
        Nie wymaga żadnych modeli
    ==================================================================================
-->


<div class="container" id="user-not-logged-in">
    <div class="jumbotron row">
        <div class="col-lg-7">
            <h1>GimBook</h1>
            <p class="lead">GimBook jest nowoczesnym dziennikiem na miare XIX wieku</p>
            <ul></ul>

            <p><a href="http://asp.net" class="btn btn-primary btn-lg">O Nas &raquo;</a></p>
            <p><a href="http://asp.net" class="btn btn-primary btn-lg">Kontakt &raquo;</a></p>
        </div>
        <div class="col-lg-4 col-lg-offset-1">
            <h2 class="text-primary">Zaloguj sie</h2>
            <form action="login" class="form-horizonal">
                <p class="form-group">
                    <label for="username">E-mail</label>
                    <input class="form-control" name="username" type="email" />
                </p>
                <p class="form-group">
                    <label for="username">Hasło</label>
                    <input class="form-control" name="username" type="password" />
                </p>
                <p>
                    <button class="btn btn-danger" type="submit">Zaloguj</button>
                </p>
            </form>
        </div>
    </div>
</div>

gimBook/Views/Home/_TeacherIndexView.cshtml
@model gimBook.ViewModels.IndexViewModel

<!--
    ==================================================================================
        Strona dla zalogowanego Nauczyciela.
        Wymagane parametry modelu to

            * Parametry użytkownika --
            * Nazwa i rok klasy podlegającej --
            * Średnia klasy podlegającej --
            * Lista Przedmiotów nauczania --

            ** Lista Przedmiotów podlegających klasie i nauczycielowi(AJAX)
            ** Lista uczniów wybranego przedmiotu(AJAX)
    ==================================================================================
-->

<script type="text/javascript">sendGradesUrl = '@Url.Action("SendGrades", "Ajax")'</script>

<div class="container" id="teacher-index-page">
    <div class="row jumbotron">
        <div class="col-md-6">
            <p><h1 class="page-header">Witaj, @Model.CurrentUser.FirstName</h1></p>
            <p>@Model.CurrentUser.FirstName @Model.CurrentUser.LastName</p>

            <p><a href="#grade-input" class="btn btn-danger btn-lg btn-block">Mój dziennik &raquo;</a></p>
            <p><a href="#student-list" class="btn btn-primary btn-lg btn-block">Moja klasa &raquo;</a></p>
        </div>
        <div class="col-md-6 text-center">

            @if (Model.UserClassAverage != 0)
            {
                <h2>Twoja klasa:</h2>
                <h1><span class="text-info">@Model.UserClass.classYear @Model.UserClass.className</span></h1>
                <h2>Średnia klasy:</h2>
                <h1 class="text-info"><span class="text-info">@string.Format("{0:0.00}", Model.UserClassAverage) </span></h1>
            }
            else
            {
                <h2> Nie masz jeszcze przypisanej klasy</h2>


                <p> Cierpliwości :)</p>
            }
        </div>
    </div>
    @if (Model.SubjectList != null)
    {
        <div class="row" id="grade-input">

            <h1 class="text-danger">Nowa Ocena:</h1>
            <h2>Wprowadź klasę</h2>
            <div class="form-group col-md-12" id="class-pick">

                <label for="class">Klasa:</label>
                <select class="form-control show-tick btn btn-danger btn-group-justified btn-lg" id="subject-picker" style="height: 50px;" data-style="btn-primary" data-width="50%">
                    <option value="default" selected="selected">Wybierz Przedmiot</option>
                    @foreach (var cl in Model.SubjectList)
                    {
                        <option value="@cl.Int">@cl.Str1 - @cl.Str2</option>
                    }
                </select>

            </div>


            <div class="row" id="student-list-top" style="display:none">
                <div id="set-all-grades-to" class="form-group col-md-12">
                    <label for="all-grades-select" class="control-label">Ustaw wszystkie oceny na: </label>
                    <select class="form-control btn btn-default btn-group-justified" name="all-grades-set" id="all-grades-set">
                        <option value="0">-- BRAK -- </option>
                        <option value="6">Celujący</option>
                        <option value="5">B.Dobry</option>
                        <option value="4">Dobry</option>
                        <option value="3">Dostateczny</option>
                        <option value="2">Dopusczający</option>
                        <option value="1">Niedostateczny</option>
                    </select>
                </div>
                <div id="set-all-mult-to" class="form-group col-md-12">
                    <label for="all-mult-select" class="control-label">Ustaw wszystkie Wagi na: </label>
                    <select class="form-control btn btn-default btn-group-justified" name="all-mult-set" id="all-mult-set">
                        <option value="4">IV</option>
                        <option value="3">III</option>
                        <option value="2">II</option>
                        <option value="1">I</option>
                    </select>
                </div>
                <div id="set-all-topics" class="col-md-12 form-group">
                    <label for="all-topic-set" class="control-label">Ustaw wszystkie tematy na:</label>
                    <input type="text" class="form-control" id="all-topic-set" name="all-topic-set" />
                </div>

                <h1 class="text-center text-danger">Wprowadź Oceny</h1>
            </div>

            <div id="student-list-grade-form" style="margin-left: 0" class="row">
                <h1 class="text-center text-info">Wybierz przedmiot z listy :)</h1>
            </div>

        </div>
    }
    else
    {
        <h1 class="text-center text-danger">Nie posiadasz jeszcze przypisanych przedmiotów</h1>
    }

    @if (Model.StudentList != null)
    {
        <div class="container" id="student-list">
            <h1 class="text-danger">
                Twoja Klasa
            </h1>
            <p>Kliknij osobę, aby edytować</p>
            <p class="text-muted">Prawo do edycji ocen i haseł ma wyłącznie administrator</p>
            <table class="table table-striped" style="font-size: 16px">
                <thead>
                    <tr>
                        <th>Imię</th>
                        <th>Nazwisko</th>
                        <th>E-Mail</th>
                        <th>Dziennik</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(var row in Model.StudentList)
                    {
                        <tr class="student-list-row">
                            <td class="student-list-f-name"><a href="@Url.Action("EditStudent", "home", new { id = @row.Id })">@row.FirstName</a></td>
                            <td class="student-list-l-name"><a href="@Url.Action("editStudent", "home", new { id = @row.Id })">@row.LastName</a></td>
                            <td class="student-list-e-mail"><a href="@Url.Action("editStudent", "home", new { id = @row.Id })">@row.EMail</a></td>
                            <td class="student-list-grades">                                
                                <div class="list-grade-table">
                                    <table class="table-hover">
                                        @foreach (var g in row.Grades)
                                        {
                                            <tr>
                                                <td>@g.SubjectName</td>
                                                <td>@g.Grade</td>
                                                <td>@g.Subject</td>
                                            </tr>
                                            <tr class="space-row"></tr>
                                        }
                                    </table>
                                </div>
                                <button class="btn btn-default grades-button">Pokaż Dziennik...</button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }

</div>